{% set name = "aws-s3-access-grants-boto3-plugin" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_s3_access_grants_boto3_plugin-{{ version }}.tar.gz
  sha256: f02fc8d3acc1906e129dba3f4c1199b9c06a5c643850e6f56b2c7bcd7550b048

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cacheout >=0.16.0
    - botocore >=1.34.70

test:
  imports:
    - aws_s3_access_grants_boto3_plugin
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/boto3-s3-access-grants-plugin
  summary: Amazon S3 Access Grants plugin for boto3
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  dev_url: https://github.com/aws/boto3-s3-access-grants-plugin

extra:
  recipe-maintainers:
    - claytonparnell
